# Nombre de tu proyecto
spring.application.name=qr-generator

# 1. Configuración de la Base de Datos H2
spring.datasource.url=jdbc:h2:mem:qrdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Permite ver la base de datos en el navegador (localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

# 2. Configuración de Swagger (Documentación API)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Para que Hibernate cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
